  - debug: msg='Writing ansible result to {{ ansibleResultFile }} with contents {{ restResult.content }}' #'

  - lineinfile: dest='{{ ansibleResultFile }}' line='{{ restResult.content }}' create='yes'
    when: restResult.content is defined
