---
- hosts: localhost 
  tasks:

  - name: Getting AssetOptions for BlockStorageTypeForExport
    debug: var=ansibleResultFile

  - file: path={{ansibleResultFile}} state=touch mode="u=rw,g=r,o=r"

  - command: /usr/bin/truncate -s 0 {{ ansibleResultFile }}

  - lineinfile: dest={{ ansibleResultFile }} line="["

  - lineinfile: 
        dest={{ ansibleResultFile }} 
        line=" {\"name\":\"Shared\",\"id\":\"shared\"},{\"name\":\"Exclusive\",\"id\":\"exclusive\"}"

  - lineinfile: dest={{ ansibleResultFile }} line="]"
